name: build-lumos

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: OpenWRT-fanboy/OpenW1700k
  REMOTE_BRANCH: lumos-AUTO
  RELEASE_PREFIX: lumos
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:  
  build:
    name: Build OpenWrt
    runs-on: ubuntu-24.04
    steps:
      - name: Free disk space on runner
        run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/ghc \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
      - name: Checkout remote repository (Openwrt repo)
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}
          fetch-depth: 0
      - name: Checkout current repository (custom files)
        uses: actions/checkout@v6
        with:
          path: custom
      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Include custom files
        run: |
          mkdir -p files/
          mv custom/user/default/files/* files/
          mv files/overview.js feeds/luci/applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
          mv files/luci-app-airoha-npu feeds/luci/applications/
          mv files/luci-app-w1700k-fancontrol feeds/luci/applications/
          ./scripts/feeds update luci
          ./scripts/feeds install luci-app-airoha-npu
          ./scripts/feeds install luci-app-w1700k-fancontrol
      - name: Configure firmware image
        run: |
          mv custom/user/${{ env.RELEASE_PREFIX }}/config.diff .config
          make defconfig
          echo CONFIG_VERSION_NUMBER=${{ env.RELEASE_PREFIX }}-SNAPSHOT >> .config
      - name: Download dependencies
        run: make -j$(($(nproc)+1)) download
      - name: Build the firmware image
        run: make -j$(($(nproc)+1)) V=sc world
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: airoha_an7581-images
          path: bin/targets/airoha/an7581

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          name: airoha_an7581-images
          path: ./firmware
      - name: Create Release
        run: |
          # Extract version code from profiles.json
          version_code=$(jq -r '.version_code' ./firmware/profiles.json)
          VERSION="${{ env.RELEASE_PREFIX }}-$(date +'%Y.%m.%d')-${version_code}"
          # Check if the release already exists
          if gh release view "$VERSION" &>/dev/null; then
            gh release delete "$VERSION" --cleanup-tag -y
          fi
          # Create the new release
          FILES_TO_UPLOAD=$(find ./firmware -maxdepth 1 -type f -name "*.bin")
          gh release create "$VERSION" $FILES_TO_UPLOAD \
            --title "$VERSION"
