name: sync-branches-to-AUTO

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: OpenWRT-fanboy/OpenW1700k

jobs:
  update:
    name: Sync ${{ matrix.environment }} branch
    runs-on: ubuntu-slim
    strategy:
      matrix:
        environment: [lumos, lumos-npu, minimal, minimal-npu]
    permissions:
      contents: write
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout AUTO repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ matrix.environment }}-AUTO
          fetch-depth: 0
          token: ${{ secrets.REPO_SECRET }}
      - name: Sync regular branch
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git switch -c ${{ matrix.environment }}
          git push --set-upstream origin ${{ matrix.environment }} --force-with-lease
